from .preprocess import Preprocess
from .upload import Upload
from .auth import Auth
from .get_district import GetDistricts
from .get_taluk import GetTaluk
from .get_village import GetVillage
from .get_block import GetBlock
from .get_survey import GetSurvey
from .get_images import GetImage
from .home import Home